# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb29854d32a094c2c2f6e3500d0354f2bf9257eaf2bf6d4d18732f66571bfc45da5782999cf4b2b56919cd57d409f78304fbcb5f5844235082a307b3ff200270

test:
  secret_key_base: 0cef477671f8caa58a6b3f7819330b1483e43dfbca4d8907270de82a98450eb515e0bccae1d37269a33998f26edadb255a919a1d7e4dbb15b5345524034f3515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
